# Generated by Django 4.1.2 on 2023-04-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auction', '0002_alter_product_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Никнейм'),
        ),
    ]
