# Generated by Django 4.1.2 on 2023-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auction', '0003_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pic',
            field=models.ImageField(null=True, upload_to='photos/users/', verbose_name='Фото'),
        ),
    ]
