# Generated by Django 4.1.2 on 2023-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auction', '0005_alter_comment_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='Валюта'),
        ),
    ]
