# Generated by Django 4.1.2 on 2023-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auction', '0006_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.CharField(default='$', max_length=255, verbose_name='Валюта'),
        ),
    ]
