# Generated by Django 4.1.2 on 2023-05-07 19:07

import app_auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auction', '0007_alter_product_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='closed_at',
            field=models.DateTimeField(default=app_auction.models.get_closed_date),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(default=app_auction.models.get_deleted_date),
        ),
    ]
