# Generated by Django 4.1.2 on 2023-05-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auction', '0008_product_closed_at_product_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsDeletedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=255, verbose_name='uuid-string')),
            ],
            options={
                'verbose_name': 'Удалённый товар',
                'verbose_name_plural': 'Удалённые товары',
            },
        ),
    ]
