# Generated by Django 4.1.2 on 2023-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auction', '0009_isdeletedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Фото'),
        ),
    ]
